name: Test building on latest MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Configure xcode usage
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Set up C++ compiler (macOS)
        run: |
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python3 -m pip install setuptools
          npm ci

      - name: Run eslint
        run: |
          npm run check

      - name: Build jsroot.js
        run: |
          npm run build

      - name: Run demos
        run: |
          cd demo/node; npm install; cd ../..
          node demo/node/makesvg.js
          node demo/node/tree_dump.js
          node demo/node/tree_draw.js
          node demo/node/selector.js
