name: Test building on latest Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        cxx: [g++-11, g++-12, g++-13]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set up C++ compiler (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.cxx }}
          sudo apt-get install -y xutils-dev libxi-dev libxxf86vm-dev x11proto-xf86vidmode-dev mesa-utils xvfb libgl1-mesa-dri libglapi-mesa libosmesa6 musl-dev libgl1-mesa-dev
          sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config
          echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          npm ci

      - name: Build jsroot.js
        run: |
          npm run build

      - name: Run demos
        run: |
          cd demo/node; npm install; cd ../..
          node demo/node/makesvg.js
          node demo/node/tree_dump.js
          node demo/node/tree_draw.js
          node demo/node/geomsvg.js
          node demo/node/selector.js
